version: '3'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./cdsl:/var/www/html/wp-content/themes/cdsl
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
